# Generated by Django 3.0.2 on 2020-03-13 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20200313_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-updated_on',)},
        ),
    ]
