# Generated by Django 3.0.2 on 2020-03-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20200313_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
