# Generated by Django 3.0.2 on 2020-03-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20200313_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_like',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
