# Generated by Django 3.0.2 on 2020-02-04 16:54

import ckeditor.fields
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComicPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='comics/')),
                ('description', ckeditor.fields.RichTextField()),
                ('caption', models.CharField(max_length=500)),
                ('chapter', models.FloatField(default=1, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('episode', models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('uploadTime', models.DateTimeField(default=datetime.datetime.now)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=15)),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.ComicPanel')),
            ],
        ),
        migrations.AddConstraint(
            model_name='comicpanel',
            constraint=models.UniqueConstraint(fields=('chapter', 'episode'), name='unique appversion'),
        ),
    ]
