# Generated by Django 3.0.2 on 2020-02-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicpanel',
            name='chapter',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='comicpanel',
            name='episode',
            field=models.IntegerField(null=True),
        ),
    ]
