# Generated by Django 3.0.2 on 2020-02-07 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicpanel',
            name='series',
            field=models.CharField(default='main', help_text='Label the series as main to be displayed on the homepage', max_length=255),
        ),
    ]
