# Generated by Django 3.0.2 on 2020-02-07 04:31

import comics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0002_auto_20200207_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicpanel',
            name='series',
            field=models.CharField(default=comics.models.getMainSeriesName, help_text='The default value is what the main Series Name is set to in Settings.py', max_length=255),
        ),
    ]
