# Generated by Django 3.0.2 on 2020-02-04 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0002_auto_20200204_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicpanel',
            name='uploadTime',
            field=models.DateField(default=datetime.date(2020, 2, 4)),
        ),
    ]
