# Generated by Django 3.0.2 on 2020-03-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0002_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicpanel',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Insert a Youtube URL if you want a video for a comic', max_length=250, null=True),
        ),
    ]
