# Generated by Django 3.0.2 on 2020-02-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0003_auto_20200204_1742'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comicpanel',
            name='unique appversion',
        ),
        migrations.AlterField(
            model_name='comicpanel',
            name='chapter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comicpanel',
            name='episode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='comicpanel',
            constraint=models.UniqueConstraint(fields=('chapter', 'episode'), name='Must be null or unique'),
        ),
    ]
