# Generated by Django 3.0.2 on 2020-02-05 05:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0004_auto_20200204_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicpanel',
            name='uploadTime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
