# Generated by Django 3.0.2 on 2020-04-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0005_auto_20200319_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicpanel',
            name='send_emails',
            field=models.BooleanField(default=True),
        ),
    ]
