# Generated by Django 3.0.2 on 2020-04-19 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='send_emails',
            field=models.BooleanField(default=True),
        ),
    ]
