# Generated by Django 3.0.2 on 2020-04-20 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20200420_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customemail',
            name='custom_recipients',
        ),
    ]
