# Generated by Django 3.0.2 on 2020-04-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_remove_customemail_custom_recipients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='key',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
